#!/bin/bash

i=1
somavalores=0
maior=0
while [ $i -le 15 ]
do
    echo "escreva o valor de $i° produto"
    read valor
    if [ $valor -gt $maior ]
    then 
         maior=$valor
    fi
    somavalores=$(($somavalores+$valor))
    i=$(($i+1))
done
somavalores=$( bc <<< "scale=2; $somavalores/15")
echo "o produto mais caro custa $maior reais"
echo "a média de valor dos produtos é $somadosvalores"
